"""acronym_mapping: auto-increment id as the primary key, drop the UUID code column

Revision ID: 5b7dea819fa4
Revises: f13a664a31b6
Create Date: 2026-10-01 12:45:00.000000

f13a664a31b6 now creates the table with `id` as the key. Databases that ran an
earlier version of it still have one of these shapes, which this converts:
  - `code` (UUID) primary key only;
  - `code` primary key plus a separate unique auto-increment `id`.
A table that already has `id` as its key and no `code` is left untouched.

Downgrade restores a UUID `code` primary key (with new UUIDs; the old ones are
gone) and keeps `id` as a unique non-key column, a shape every model version reads.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7dea819fa4'
down_revision: Union[str, Sequence[str], None] = 'f13a664a31b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = 'acronym_mapping'
PK_NAME = 'acronym_mapping_pkey'


def upgrade() -> None:
    """Upgrade schema."""
    inspector = sa.inspect(op.get_bind())
    columns = {c['name'] for c in inspector.get_columns(TABLE)}
    pk = inspector.get_pk_constraint(TABLE)
    if pk['constrained_columns'] == ['id'] and 'code' not in columns:
        return

    if pk['name']:
        op.drop_constraint(pk['name'], TABLE, type_='primary')
    if 'code' in columns:
        op.drop_column(TABLE, 'code')

    if 'id' in columns:
        # The old non-key id is already an identity column; its own unique
        # constraint becomes redundant once it is the primary key.
        for unique in inspector.get_unique_constraints(TABLE):
            if unique['column_names'] == ['id']:
                op.drop_constraint(unique['name'], TABLE, type_='unique')
        op.create_primary_key(PK_NAME, TABLE, ['id'])
    else:
        # Postgres numbers the existing rows when the identity column is added.
        op.execute(
            f'ALTER TABLE {TABLE} ADD COLUMN id BIGINT '
            f'GENERATED BY DEFAULT AS IDENTITY CONSTRAINT {PK_NAME} PRIMARY KEY'
        )


def downgrade() -> None:
    """Downgrade schema."""
    # An app rolled back to a version that reads `code` needs the column back.
    # Postgres fills new UUIDs for the existing rows; the original ones are gone.
    pk = sa.inspect(op.get_bind()).get_pk_constraint(TABLE)
    op.execute(f'ALTER TABLE {TABLE} ADD COLUMN code UUID NOT NULL DEFAULT gen_random_uuid()')
    if pk['name']:
        op.drop_constraint(pk['name'], TABLE, type_='primary')
    op.create_unique_constraint('acronym_mapping_id_key', TABLE, ['id'])
    op.create_primary_key(PK_NAME, TABLE, ['code'])
